### ISSUE TITLE
Any benchmarking ?

### ISSUE THREAD

**Issue by thebentern** [hwwong/ESP_influxdb#3]
Hi,

Thanks for your work on this project. I'm curious to see how posting data to something that is made to handle a significant amount of throughput of time-series data like InfluxDb would compare in throughput vs other options such as MQTT or even Redis. I ask because I am looking for the fastest possible way to log data over the air (particularly smallest delay between datapoints sent). InfluxDB is a wonderful backend for this sort of application, but I fear that the limiting factor may be the limitations of the http client in the esp8266 arduino libraries. I was wondering if you had done any benchmarking to compare this to other other options? If not, in my quest to find the right solution for my specific application, I may be able to share some results of my own.

Thanks again for your work on this.
-Ben

**Comment by hwwong** [comment]
Hello Ben,

Yes, the HTTP limits the transfer rate. I haven't tried any benchmark for my program. but I had tried log batch data in the memory to reduce the delay between datapoints reading and then send to Influxdb batch by batch.   

Best regards, 
hwwong
